Instance:
  Mapping:
    attachedDisk: "disks"
    bootDisk: "disks"
    scratchDisk: "disks"
    networkInterface: "networkInterfaces"
    ipv6AccessConfig: "ipv6AccessConfigs"
    aliasIpRange: "aliasIpRanges"
    accessConfig:  "accessConfigs"
    currentStatus: "status"
    networkIp: "networkIP"
    natIp: "natIP"
    image: "sourceImage"
    size: "diskSizeGb"
    type: "diskType"
    serviceAccount: "serviceAccounts"
    guestAccelerator: "guestAccelerators"
    type: "acceleratorType"
    count: "acceleratorCount"
  ExactMapping:
    tags.items: "tags"
    tags.fingerprint: "tagsFingerprint"
    disks.diskEncryptionKey.rawKey: "attachedDisk.diskEncryptionKeyRaw"
    disks.diskEncryptionKey.sha256: "attachedDisk.diskEncryptionKeySha256"
    disks.diskEncryptionKey.kmsKeyName: "attachedDisk.kmsKeySelfLink"
    metadata.fingerprint: "metadataFingerprint"
    metadata.items.key: "metadata"
    metadata.items.value: "metadata"
    reservationAffinity.consumeReservationType: "reservationAffinity.type"
    reservationAffinity.key: "reservationAffinity.specificReservation.key"
    reservationAffinity.values: "reservationAffinity.specificReservation.values"
    displayDevice.enableDisplay: "enableDisplay"
  Exclude:
  - kind
  - statusMessage
  - networkInterfaces.kind
  - scheduling.locationHint
  - networkInterfaces.accessConfigs.kind
  - networkInterfaces.ipv6AccessConfigs.kind
  - networkInterfaces.fingerprint
  - networkInterfaces.networkAttachment
  - disks.kind
  - disks.type
  - disks.savedState
  - disks.index
  - disks.boot
  - disks.initializeParams.licenses
  - disks.licenses
  - disks.forceAttach
  - disks.shieldedInstanceInitialState.pk.content
  - disks.shieldedInstanceInitialState.pk.fileType
  - disks.shieldedInstanceInitialState.keks.content
  - disks.shieldedInstanceInitialState.keks.fileType
  - disks.shieldedInstanceInitialState.dbs.content
  - disks.shieldedInstanceInitialState.dbs.fileType
  - disks.shieldedInstanceInitialState.dbxs.content
  - disks.shieldedInstanceInitialState.dbxs.fileType
  - metadata.kind
  - startRestricted
  - sourceMachineImage
  - fingerprint
  - privateIpv6GoogleAccess
  - satisfiesPzs
  - satisfiesPzi
